# Generated by Django 3.2.5 on 2023-11-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='blog_article_info',
        ),
    ]
